# Generated by Django 4.2.7 on 2023-12-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegrade',
            name='grade_max',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
