# Generated by Django 4.1.4 on 2023-10-24 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=64)),
                ('max_score', models.IntegerField(default=0)),
                ('min_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('level', models.PositiveIntegerField(default=1)),
                ('year', models.CharField(max_length=12)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility', to='app.school')),
            ],
        ),
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstSemester', models.IntegerField(default=0)),
                ('secondSemester', models.IntegerField(default=0)),
                ('thirdSemester', models.IntegerField(default=0)),
                ('fourthSemester', models.IntegerField(default=0)),
                ('final', models.IntegerField(default=0)),
                ('year', models.CharField(max_length=12)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseGrade', to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeValue', models.IntegerField(default=0)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('week', models.IntegerField(default=1)),
                ('notes', models.CharField(default='None', max_length=516)),
                ('year', models.CharField(max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissionDate', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('altName', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('social', models.CharField(blank=True, max_length=64, null=True)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('qualification', models.CharField(blank=True, max_length=64, null=True)),
                ('birthday', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SchoolTeacher', to='app.school')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='app.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='app.teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='gradebook',
            name='student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='altname',
            new_name='altName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='alt_contact',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='alt_name',
            new_name='social',
        ),
        migrations.RemoveField(
            model_name='student',
            name='altschool',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='start_date',
        ),
        migrations.AddField(
            model_name='student',
            name='firstName',
            field=models.CharField(default='FirstName', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='lastName',
            field=models.CharField(default='LastName', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='altName',
            field=models.CharField(default='FirstName', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='FirstName', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='lastName', max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='gradebook',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit', to='app.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='app.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicGrade', to='app.assignment'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseGrade_student', to='app.student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='app.course'),
        ),
    ]
