# Generated by Django 4.2.7 on 2023-12-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coursegrade_grade_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='semester',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='type',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
