# Generated by Django 4.2.7 on 2023-12-31 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_course_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
