# Generated by Django 4.1.4 on 2023-10-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_assignment_course_coursegrade_grade_studentcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='altName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
