# Generated by Django 4.2.7 on 2023-12-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_coursegrade_semester_alter_coursegrade_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='grade_value',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
