# Generated by Django 4.1.4 on 2023-10-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_altname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='School',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='altname',
            new_name='altName',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='birthday',
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.TimeField(default='0:0:0'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(default='0:0:0'),
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
