# Generated by Django 4.2.7 on 2023-12-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_studentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='student_Courses', to='app.course'),
        ),
    ]
