# Generated by Django 4.2.7 on 2023-12-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_coursegrade_grade_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='grade_letter',
            field=models.CharField(blank=True, default='none', max_length=12),
        ),
    ]
