# Generated by Django 4.1.4 on 2023-10-26 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_school_course_school_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='max_score',
            new_name='maxScore',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='min_score',
            new_name='minScore',
        ),
    ]
