# Generated by Django 4.1.4 on 2023-11-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_max_score_assignment_maxscore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
    ]
