# Generated by Django 4.2.7 on 2023-12-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_grade_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='notes',
            field=models.CharField(blank=True, max_length=516),
        ),
        migrations.AlterField(
            model_name='grade',
            name='semester',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
