# Generated by Django 4.2.7 on 2023-12-31 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_coursegrade_grade_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursegrade',
            old_name='grade_value',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='coursegrade',
            old_name='grade_max',
            new_name='max_score',
        ),
    ]
