# Generated by Django 4.1.4 on 2023-11-25 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_user_firstname_remove_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='app.teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.TimeField(blank=True, default='0:0:0'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(blank=True, default='0:0:0'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='altName',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.DeleteModel(
            name='TeacherCourse',
        ),
    ]
