# Generated by Django 4.2.7 on 2023-12-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_grade_value_coursegrade_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='grade_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
