# Generated by Django 4.2.7 on 2023-12-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_coursegrade_grade_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='grade_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
