# Generated by Django 4.2.7 on 2023-12-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
    ]
