# Generated by Django 4.2.7 on 2023-12-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_course_year_alter_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='access',
            field=models.CharField(default='aaa-aaa-aaa', max_length=11),
        ),
    ]
