# Generated by Django 4.2.7 on 2023-12-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_school_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='access',
            field=models.CharField(default='aaa-aaa-aaa', max_length=14),
        ),
    ]
