# Generated by Django 4.2.7 on 2023-12-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_school_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='access',
            new_name='code',
        ),
    ]
