# Generated by Django 4.2.7 on 2023-12-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_access_school_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='maxScore',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='minScore',
            new_name='min_score',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='coursegrade',
            old_name='firstSemester',
            new_name='first_semester',
        ),
        migrations.RenameField(
            model_name='coursegrade',
            old_name='fourthSemester',
            new_name='fourth_semester',
        ),
        migrations.RenameField(
            model_name='coursegrade',
            old_name='secondSemester',
            new_name='second_semester',
        ),
        migrations.RenameField(
            model_name='coursegrade',
            old_name='thirdSemester',
            new_name='third_semester',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='gradeValue',
            new_name='grade_value',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='gradeLevel',
            new_name='grade_level',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='altName',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='studentcourse',
            old_name='admissionDate',
            new_name='admission_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='altName',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='school',
            name='altName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
