# Generated by Django 4.2.7 on 2023-12-19 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admins',
            field=models.ManyToManyField(related_name='admin_school', to=settings.AUTH_USER_MODEL),
        ),
    ]
