# Generated by Django 4.2.7 on 2023-12-21 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_school_admins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='present',
            new_name='attendance',
        ),
        migrations.RenameField(
            model_name='coursegrade',
            old_name='final',
            new_name='grade_value',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='admin',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='tag',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='end_date',
            new_name='joined',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='start_date',
            new_name='released',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='event',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.RemoveField(
            model_name='coursegrade',
            name='first_semester',
        ),
        migrations.RemoveField(
            model_name='coursegrade',
            name='fourth_semester',
        ),
        migrations.RemoveField(
            model_name='coursegrade',
            name='second_semester',
        ),
        migrations.RemoveField(
            model_name='coursegrade',
            name='third_semester',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade_level',
        ),
        migrations.AddField(
            model_name='assignment',
            name='letter',
            field=models.CharField(default='None', max_length=12),
        ),
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AddField(
            model_name='attendance',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='grade_type',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='grade_letter',
            field=models.CharField(default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='type',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='grade',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignmentGrade', to='app.assignment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_letter',
            field=models.CharField(default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='year',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='app.school'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='admission_date',
            field=models.DateField(),
        ),
    ]
