# Generated by Django 4.2.7 on 2023-12-25 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_school_name_alter_studentcourse_admission_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='creator',
            new_name='master',
        ),
    ]
