# Generated by Django 4.2.7 on 2023-12-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_attendance_added_by_course_added_by_student_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='code',
        ),
        migrations.AddField(
            model_name='school',
            name='admin_code',
            field=models.CharField(default='a-aaa-aaa-aaa', max_length=12),
        ),
        migrations.AddField(
            model_name='school',
            name='parent_code',
            field=models.CharField(default='a-aaa-aaa-aaa', max_length=12),
        ),
        migrations.AddField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(default='a-aaa-aaa-aaa', max_length=12),
        ),
    ]
