# Generated by Django 4.2.7 on 2023-12-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_school_code_school_admin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='admin_code',
            field=models.CharField(default='a-aaaa-aaaa-aaaa', max_length=16),
        ),
        migrations.AlterField(
            model_name='school',
            name='parent_code',
            field=models.CharField(default='a-aaaa-aaaa-aaaa', max_length=16),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(default='a-aaaa-aaaa-aaaa', max_length=16),
        ),
    ]
