# Generated by Django 4.2.7 on 2023-12-30 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_grade_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admins',
            field=models.ManyToManyField(related_name='student_teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
