# Generated by Django 4.2.7 on 2023-12-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_student_admins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admins',
            new_name='teachers',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='student_Courses', to='app.course'),
        ),
    ]
