# Generated by Django 4.2.7 on 2023-12-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rename_admins_student_teachers_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
