# Generated by Django 4.2.7 on 2023-12-30 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_student_course_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='released',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='joined',
            new_name='start_date',
        ),
    ]
