# Generated by Django 4.2.7 on 2023-12-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_student_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='exit_reason',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
