# Generated by Django 4.2.7 on 2023-12-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_student_exit_student_exit_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='exit_reason',
            new_name='exit_type',
        ),
    ]
