# Generated by Django 4.2.7 on 2023-12-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_rename_exit_reason_student_exit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='exit',
            new_name='admitted',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='exit_type',
            new_name='nonadmission_type',
        ),
    ]
