# Generated by Django 4.2.7 on 2023-12-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_rename_exit_student_admitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students_enrolled',
            field=models.ManyToManyField(related_name='course_students', to='app.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admitted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
